name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: van9biceps/LAB4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: docs/html
          config_file: Doxyfile
