name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

- name: Doxygen GitHub Pages Deploy Action

  uses: DenverCoder1/doxygen-github-pages-action@v1.3.0

