name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: LAB4
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: docs/html
          config_file: Doxyfile
